let fruits = ["apple", "banana", "cherry"];
console.log("Fruits Array:", fruits);
console.log("First Fruit:", fruits[0]);
console.log("Second Fruit:", fruits[1]);
console.log("Third Fruit:", fruits[2]);
fruits.push("orange");
console.log("After Adding Orange:", fruits);
fruits.pop();
console.log("After Removing Last Fruit:", fruits);
fruits.unshift("kiwi");
console.log("After Adding Kiwi at Start:", fruits);
fruits.shift();
console.log("After Removing First Fruit:", fruits);
console.log("Fruits Length:", fruits.length);
console.log("Is Fruits an Array?", Array.isArray(fruits));
console.log("Index of Banana:", fruits.indexOf("banana"));
console.log("Sliced Fruits (1 to 2):", fruits.slice(1, 3));
console.log("Joined Fruits:", fruits.join(", "));
console.log("Reversed Fruits:", fruits.reverse());
console.log("Sorted Fruits:", fruits.sort());
console.log("Fruits Array After Sorting:", fruits);
console.log("Fruits Array After Reversing:", fruits.reverse());
console.log("Fruits Array After Sorting Again:", fruits.sort());
console.log("Fruits Array After Reversing Again:", fruits.reverse());
